"""
Knowledge level taxonomy for the Secure Blackboard / GraphState SRE system.

The four levels enforce a strict epistemic hierarchy:
    OBSERVED     → raw telemetry directly read from the monitored cluster
    DERIVED      → deterministic computation from telemetry (no LLM reasoning)
    HYPOTHESIZED → abductive claim generated by an LLM investigator
    VERIFIED     → hypothesis that has survived structural, temporal, and empirical verification

Core Invariant:
    HYPOTHESIS ≠ FACT
    Agents cannot self-promote claims to VERIFIED.
    Only the causal verification engine / diagnosis gate can make this transition.
"""

from enum import Enum


class KnowledgeLevel(str, Enum):
    OBSERVED = "observed"
    DERIVED = "derived"
    HYPOTHESIZED = "hypothesized"
    VERIFIED = "verified"

    @property
    def rank(self) -> int:
        """Higher rank indicates higher epistemic certainty."""
        _ranks = {
            KnowledgeLevel.OBSERVED: 1,
            KnowledgeLevel.DERIVED: 2,
            KnowledgeLevel.HYPOTHESIZED: 1,
            KnowledgeLevel.VERIFIED: 3,
        }
        return _ranks[self]

    def can_transition_to(self, target: "KnowledgeLevel", by_role: str) -> bool:
        """
        Deterministic transition policy:
        - Investigators can only write OBSERVED, DERIVED, and HYPOTHESIZED.
        - Only the verifier / gate can promote to VERIFIED.
        """
        if target == KnowledgeLevel.VERIFIED:
            return by_role in ("verifier", "diagnosis_gate", "policy_engine")
        if target == KnowledgeLevel.HYPOTHESIZED:
            return True
        return False
